Add retry for guacone osv
guacsec/guac pull request #1363
Opened 2023-10-06 17:32 UTC by naveensrinivasan

# Description of the PR
- https://github.com/guacsec/guac/issues/1099
- Add `backoff` package for retrying operations
- Add constants for backoff configuration
- This is done at the moment for guacone osv. In the subsequent PR's we can do it for others if we agree with the present implementation.

# PR Checklist

- [ ] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

2023-10-19 13:55 UTC, pxp928 commented
@naveensrinivasan can you rebase and we can get this reviewed and merged.

2023-10-19 18:26 UTC, lumjjb requested changes

2023-10-19 18:26 UTC, lumjjb commented on cmd/guacone/cmd/osv.go
> +			signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
i think we don't want to call the syscall in a loop for every operation, we will want to only do this once.

2023-10-20 20:20 UTC, naveensrinivasan commented
Closing for #1421

2023-10-20 20:20 UTC, closed without merging